### ISSUE TITLE
Casts inside other parentheses

### ISSUE THREAD

**Issue by mcavanagh** [Platin21/ion.tmbundle#2]
Thanks for making this syntax def - I'm already getting good use out of it.

Spotted this issue when a cast is inside more parentheses:

![image](https://user-images.githubusercontent.com/6319592/39066161-104cc736-44cc-11e8-9266-13cc2bfa543e.png)

See how it highlights the closing bracket of the cast as part of the type name.

**Comment by Platin21** [comment]
Yeah will look it up. Is probably only simple change from .* to [^\[\]\(\)\{\}]
Wich Editor is it? As some errors did only occur in sublime/vscode

**Comment by mcavanagh** [comment]
Sublimetext 3

**Comment by Platin21** [comment]
Yeah, fixed checkout the new version adds some sublime stuff.
