### ISSUE TITLE
Problem's with return type highlighting.

### ISSUE THREAD

**Issue by Platin21** [Platin21/ion.tmbundle#4]
Also `char const*` as return type breaks `:` highlighting. Better support for qualifiers.

**Comment by dotbmp** [comment]
additionally this happens with regular decls, i.e. `var foo : char const*;`; the `:` wouldn't highlight. Almost certainly the weird ambiguity of `const` at play, I really hope Per finds a better way than the C way of handling that.

**Comment by Platin21** [comment]
This is now working will upload it directly.

**Comment by Platin21** [comment]
Fixed this thing happening hopefully!
